infix using "C:\COUNTRIES\AM72\AMHR72FL.dct"

label variable hhid     "Case Identification"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv008a   "Date of interview Century Day Code (CDC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv011    "Number of eligible men in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "Household selected for male interview"
label variable hv028    "Household weight for male subsample (6 decimals)"
label variable hv030    "Field supervisor"
label variable hv031    "Field editor"
label variable hv032    "Office editor"
label variable hv035    "Number of eligible children for height and weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "Total adults measured"
label variable hv042    "Household selected for hemoglobin"
label variable hv044    "Household selected for Domestic Violence module"
label variable hv045a   "Language of questionnaire"
label variable hv045b   "Language of interview"
label variable hv045c   "Native language of respondent"
label variable hv046    "Translator used"
label variable hv801    "Time interview started (hhmm - 24 hour clock)"
label variable hv802    "Time interview ended (hhmm - 24 hour clock)"
label variable hv803    "Length of interview in minutes"
label variable hv804    "Number of visits for biomarker"
label variable hv807d   "Day of biomarker visit"
label variable hv807m   "Month of biomarker visit"
label variable hv807y   "Year of biomarker visit"
label variable hv807c   "Date of biomarker (CMC)"
label variable hv807a   "Date of biomarker Century Day Code (CDC)"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv201a   "Water not available for at least a day last two weeks"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "NA - Has mosquito bed net for sleeping"
label variable hv228    "NA - Children under 5 slept under mosquito bed net last night"
label variable hv230a   "Place where household members wash their hands"
label variable hv230b   "Presence of water at hand washing place"
label variable hv232    "Items present: Soap or detergent"
label variable hv232b   "Items present: Ash, mud, sand"
label variable hv232c   "NA - Items present: CS"
label variable hv232d   "NA - Items present: CS"
label variable hv232e   "NA - Items present: CS"
label variable hv232y   "Items present: None"
label variable hv234    "Result of salt test for iodine (PPM)"
label variable hv234a   "NA - Result of salt test for iodine"
label variable hv235    "Location of source for water"
label variable hv236    "NA - Person fetching water"
label variable hv237    "Anything done to water to make safe to drink"
label variable hv237a   "Water usually treated by: boil"
label variable hv237b   "Water usually treated by: add bleach/chlorine"
label variable hv237c   "Water usually treated by: strain through a cloth"
label variable hv237d   "Water usually treated by: use water filter"
label variable hv237e   "Water usually treated by: solar disinfection"
label variable hv237f   "Water usually treated by: let it stand and settle"
label variable hv237g   "NA - Water usually treated by: CS"
label variable hv237h   "NA - Water usually treated by: CS"
label variable hv237i   "NA - Water usually treated by: CS"
label variable hv237j   "NA - Water usually treated by: CS"
label variable hv237k   "NA - Water usually treated by: CS"
label variable hv237x   "Water usually treated by: other"
label variable hv237z   "Water usually treated by: don't know"
label variable hv238    "Number of households sharing toilet"
label variable hv238a   "Location of toilet facility"
label variable hv239    "NA - Food cooked on stove or open fire"
label variable hv240    "NA - Household has a chimney, hood or neither"
label variable hv241    "Food cooked in the house/ separate building/ outdoors"
label variable hv242    "Household has separate room used as kitchen"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "Has watch"
label variable hv243c   "Has animal-drawn cart"
label variable hv243d   "Has boat with a motor"
label variable hv243e   "Has a computer"
label variable hv244    "Owns land usable for agriculture"
label variable hv245    "Hectares of agricultural land (1 decimal)"
label variable hv246    "Owns livestock, herds or farm animals"
label variable hv246a   "Owns cattle"
label variable hv246b   "Owns cows/ bulls"
label variable hv246c   "Owns horses/ donkeys/ mules"
label variable hv246d   "Owns goats"
label variable hv246e   "Owns sheep"
label variable hv246f   "Owns chickens/poultry"
label variable hv246g   "Owns pigs"
label variable hv246h   "Owns rabbits"
label variable hv246i   "Owns fur animals"
label variable hv246j   "Owns beehives"
label variable hv246k   "NA - Owns CS"
label variable hv247    "Has bank account"
label variable hv252    "Frequency household members smoke inside the house"
label variable hv253    "NA - Has dwelling been sprayed against mosquitoes in last 12 months"
label variable hv253a   "NA - Dwelling sprayed by: government worker/program"
label variable hv253b   "NA - Dwelling sprayed by: private company"
label variable hv253c   "NA - Dwelling sprayed by: NGO"
label variable hv253d   "NA - Dwelling sprayed by: CS"
label variable hv253e   "NA - Dwelling sprayed by: CS"
label variable hv253f   "NA - Dwelling sprayed by: CS"
label variable hv253g   "NA - Dwelling sprayed by: CS"
label variable hv253h   "NA - Dwelling sprayed by: CS"
label variable hv253x   "NA - Dwelling sprayed by: other"
label variable hv253z   "NA - Dwelling sprayed by: don't know"
label variable hv270    "Wealth index combined"
label variable hv271    "Wealth index factor score combined (5 decimals)"
label variable hv270a   "Wealth index for urban/rural"
label variable hv271a   "Wealth index factor score for urban/rural (5 decimals)"
label variable hml1     "NA - Number of mosquito bed nets"
label variable hml1a    "NA - Number of mosquito bed nets with specific information"
label variable hml2     "NA - Number of children under mosquito bed net previous night"
label variable chl0     "NA - Number of de-jure children 5-14 for child labor module"
label variable scdweight "Child discipline weight (6 decimals)"
label variable sh121g   "Washing machine"
label variable sh121h   "Vacuum cleaner"
label variable sh121i   "Video camera"
label variable sh121j   "Table"
label variable sh121k   "Chair"
label variable sh121l   "Sofa or divan"
label variable sh121m   "Bed"
label variable sh121n   "Buffet"
label variable sh121o   "Air conditioner"
label variable sh121p   "DVD player"
label variable sh121q   "Dish antenna"
label variable sh121r   "Freezer"
label variable sh121s   "Sewing machine"
label variable sh121t   "Carpet"
label variable sh121u   "Internet"
label variable sh125a   "Received a poverty family benefit in the last 6 months"
label variable sh125b   "Received an emergency benefit benefit in the last 6 months"
label variable sh125c   "Received a Government order in the last 6 months"
label variable sh127    "Did your household register or update their registration in the family benefit p"
label variable sh128m   "Method to get to facility"
label variable sh128n   "Number of minutes"
label variable sh31     "Total number of children age 1-14 years"
label variable sh39l    "HH line number of selected child"
label variable sh39r    "Rank number of selected child"
label variable sh39a    "Age of selected child"
label variable sh42     "Line number from household listing"
label variable sh43a    "Took away privileges"
label variable sh43b    "Explained wrong behavior"
label variable sh43c    "Shook him/her"
label variable sh43d    "Shouted, yelled, screamed"
label variable sh43e    "Gave something else to do"
label variable sh43f    "Hit on bottom with bare hand"
label variable sh43g    "Hit with hard object"
label variable sh43h    "Called name"
label variable sh43i    "Hit on head/face/ears"
label variable sh43j    "Hit on hand/arm/leg"
label variable sh43k    "Bit him/her up"
label variable sh44     "Child needs to be physically punished"
label variable sh120    "Square meters for agricultural land"
label variable sh51     "Total number of women age 15-49 years"
label variable hvidx_01 "Line number"
label variable hvidx_02 "Line number"
label variable hvidx_03 "Line number"
label variable hvidx_04 "Line number"
label variable hvidx_05 "Line number"
label variable hvidx_06 "Line number"
label variable hvidx_07 "Line number"
label variable hvidx_08 "Line number"
label variable hvidx_09 "Line number"
label variable hvidx_10 "Line number"
label variable hvidx_11 "Line number"
label variable hv101_01 "Relationship to head"
label variable hv101_02 "Relationship to head"
label variable hv101_03 "Relationship to head"
label variable hv101_04 "Relationship to head"
label variable hv101_05 "Relationship to head"
label variable hv101_06 "Relationship to head"
label variable hv101_07 "Relationship to head"
label variable hv101_08 "Relationship to head"
label variable hv101_09 "Relationship to head"
label variable hv101_10 "Relationship to head"
label variable hv101_11 "Relationship to head"
label variable hv102_01 "Usual resident"
label variable hv102_02 "Usual resident"
label variable hv102_03 "Usual resident"
label variable hv102_04 "Usual resident"
label variable hv102_05 "Usual resident"
label variable hv102_06 "Usual resident"
label variable hv102_07 "Usual resident"
label variable hv102_08 "Usual resident"
label variable hv102_09 "Usual resident"
label variable hv102_10 "Usual resident"
label variable hv102_11 "Usual resident"
label variable hv103_01 "Slept last night"
label variable hv103_02 "Slept last night"
label variable hv103_03 "Slept last night"
label variable hv103_04 "Slept last night"
label variable hv103_05 "Slept last night"
label variable hv103_06 "Slept last night"
label variable hv103_07 "Slept last night"
label variable hv103_08 "Slept last night"
label variable hv103_09 "Slept last night"
label variable hv103_10 "Slept last night"
label variable hv103_11 "Slept last night"
label variable hv104_01 "Sex of household member"
label variable hv104_02 "Sex of household member"
label variable hv104_03 "Sex of household member"
label variable hv104_04 "Sex of household member"
label variable hv104_05 "Sex of household member"
label variable hv104_06 "Sex of household member"
label variable hv104_07 "Sex of household member"
label variable hv104_08 "Sex of household member"
label variable hv104_09 "Sex of household member"
label variable hv104_10 "Sex of household member"
label variable hv104_11 "Sex of household member"
label variable hv105_01 "Age of household members"
label variable hv105_02 "Age of household members"
label variable hv105_03 "Age of household members"
label variable hv105_04 "Age of household members"
label variable hv105_05 "Age of household members"
label variable hv105_06 "Age of household members"
label variable hv105_07 "Age of household members"
label variable hv105_08 "Age of household members"
label variable hv105_09 "Age of household members"
label variable hv105_10 "Age of household members"
label variable hv105_11 "Age of household members"
label variable hv106_01 "Highest educational level attained"
label variable hv106_02 "Highest educational level attained"
label variable hv106_03 "Highest educational level attained"
label variable hv106_04 "Highest educational level attained"
label variable hv106_05 "Highest educational level attained"
label variable hv106_06 "Highest educational level attained"
label variable hv106_07 "Highest educational level attained"
label variable hv106_08 "Highest educational level attained"
label variable hv106_09 "Highest educational level attained"
label variable hv106_10 "Highest educational level attained"
label variable hv106_11 "Highest educational level attained"
label variable hv107_01 "Highest year of education completed"
label variable hv107_02 "Highest year of education completed"
label variable hv107_03 "Highest year of education completed"
label variable hv107_04 "Highest year of education completed"
label variable hv107_05 "Highest year of education completed"
label variable hv107_06 "Highest year of education completed"
label variable hv107_07 "Highest year of education completed"
label variable hv107_08 "Highest year of education completed"
label variable hv107_09 "Highest year of education completed"
label variable hv107_10 "Highest year of education completed"
label variable hv107_11 "Highest year of education completed"
label variable hv108_01 "Education completed in single years"
label variable hv108_02 "Education completed in single years"
label variable hv108_03 "Education completed in single years"
label variable hv108_04 "Education completed in single years"
label variable hv108_05 "Education completed in single years"
label variable hv108_06 "Education completed in single years"
label variable hv108_07 "Education completed in single years"
label variable hv108_08 "Education completed in single years"
label variable hv108_09 "Education completed in single years"
label variable hv108_10 "Education completed in single years"
label variable hv108_11 "Education completed in single years"
label variable hv109_01 "Educational attainment"
label variable hv109_02 "Educational attainment"
label variable hv109_03 "Educational attainment"
label variable hv109_04 "Educational attainment"
label variable hv109_05 "Educational attainment"
label variable hv109_06 "Educational attainment"
label variable hv109_07 "Educational attainment"
label variable hv109_08 "Educational attainment"
label variable hv109_09 "Educational attainment"
label variable hv109_10 "Educational attainment"
label variable hv109_11 "Educational attainment"
label variable hv110_01 "NA - Member still in school"
label variable hv110_02 "NA - Member still in school"
label variable hv110_03 "NA - Member still in school"
label variable hv110_04 "NA - Member still in school"
label variable hv110_05 "NA - Member still in school"
label variable hv110_06 "NA - Member still in school"
label variable hv110_07 "NA - Member still in school"
label variable hv110_08 "NA - Member still in school"
label variable hv110_09 "NA - Member still in school"
label variable hv110_10 "NA - Member still in school"
label variable hv110_11 "NA - Member still in school"
label variable hv111_01 "Mother alive"
label variable hv111_02 "Mother alive"
label variable hv111_03 "Mother alive"
label variable hv111_04 "Mother alive"
label variable hv111_05 "Mother alive"
label variable hv111_06 "Mother alive"
label variable hv111_07 "Mother alive"
label variable hv111_08 "Mother alive"
label variable hv111_09 "Mother alive"
label variable hv111_10 "Mother alive"
label variable hv111_11 "Mother alive"
label variable hv112_01 "Mother's line number"
label variable hv112_02 "Mother's line number"
label variable hv112_03 "Mother's line number"
label variable hv112_04 "Mother's line number"
label variable hv112_05 "Mother's line number"
label variable hv112_06 "Mother's line number"
label variable hv112_07 "Mother's line number"
label variable hv112_08 "Mother's line number"
label variable hv112_09 "Mother's line number"
label variable hv112_10 "Mother's line number"
label variable hv112_11 "Mother's line number"
label variable hv113_01 "Father alive"
label variable hv113_02 "Father alive"
label variable hv113_03 "Father alive"
label variable hv113_04 "Father alive"
label variable hv113_05 "Father alive"
label variable hv113_06 "Father alive"
label variable hv113_07 "Father alive"
label variable hv113_08 "Father alive"
label variable hv113_09 "Father alive"
label variable hv113_10 "Father alive"
label variable hv113_11 "Father alive"
label variable hv114_01 "Father's line number"
label variable hv114_02 "Father's line number"
label variable hv114_03 "Father's line number"
label variable hv114_04 "Father's line number"
label variable hv114_05 "Father's line number"
label variable hv114_06 "Father's line number"
label variable hv114_07 "Father's line number"
label variable hv114_08 "Father's line number"
label variable hv114_09 "Father's line number"
label variable hv114_10 "Father's line number"
label variable hv114_11 "Father's line number"
label variable hv115_01 "Current marital status"
label variable hv115_02 "Current marital status"
label variable hv115_03 "Current marital status"
label variable hv115_04 "Current marital status"
label variable hv115_05 "Current marital status"
label variable hv115_06 "Current marital status"
label variable hv115_07 "Current marital status"
label variable hv115_08 "Current marital status"
label variable hv115_09 "Current marital status"
label variable hv115_10 "Current marital status"
label variable hv115_11 "Current marital status"
label variable hv116_01 "Currently, formerly, never married"
label variable hv116_02 "Currently, formerly, never married"
label variable hv116_03 "Currently, formerly, never married"
label variable hv116_04 "Currently, formerly, never married"
label variable hv116_05 "Currently, formerly, never married"
label variable hv116_06 "Currently, formerly, never married"
label variable hv116_07 "Currently, formerly, never married"
label variable hv116_08 "Currently, formerly, never married"
label variable hv116_09 "Currently, formerly, never married"
label variable hv116_10 "Currently, formerly, never married"
label variable hv116_11 "Currently, formerly, never married"
label variable hv117_01 "Eligibility for female interview"
label variable hv117_02 "Eligibility for female interview"
label variable hv117_03 "Eligibility for female interview"
label variable hv117_04 "Eligibility for female interview"
label variable hv117_05 "Eligibility for female interview"
label variable hv117_06 "Eligibility for female interview"
label variable hv117_07 "Eligibility for female interview"
label variable hv117_08 "Eligibility for female interview"
label variable hv117_09 "Eligibility for female interview"
label variable hv117_10 "Eligibility for female interview"
label variable hv117_11 "Eligibility for female interview"
label variable hv118_01 "Eligibility for male interview"
label variable hv118_02 "Eligibility for male interview"
label variable hv118_03 "Eligibility for male interview"
label variable hv118_04 "Eligibility for male interview"
label variable hv118_05 "Eligibility for male interview"
label variable hv118_06 "Eligibility for male interview"
label variable hv118_07 "Eligibility for male interview"
label variable hv118_08 "Eligibility for male interview"
label variable hv118_09 "Eligibility for male interview"
label variable hv118_10 "Eligibility for male interview"
label variable hv118_11 "Eligibility for male interview"
label variable hv120_01 "Children eligibility for height/weight and hemoglobin"
label variable hv120_02 "Children eligibility for height/weight and hemoglobin"
label variable hv120_03 "Children eligibility for height/weight and hemoglobin"
label variable hv120_04 "Children eligibility for height/weight and hemoglobin"
label variable hv120_05 "Children eligibility for height/weight and hemoglobin"
label variable hv120_06 "Children eligibility for height/weight and hemoglobin"
label variable hv120_07 "Children eligibility for height/weight and hemoglobin"
label variable hv120_08 "Children eligibility for height/weight and hemoglobin"
label variable hv120_09 "Children eligibility for height/weight and hemoglobin"
label variable hv120_10 "Children eligibility for height/weight and hemoglobin"
label variable hv120_11 "Children eligibility for height/weight and hemoglobin"
label variable hv121_01 "Member attended school during current school year"
label variable hv121_02 "Member attended school during current school year"
label variable hv121_03 "Member attended school during current school year"
label variable hv121_04 "Member attended school during current school year"
label variable hv121_05 "Member attended school during current school year"
label variable hv121_06 "Member attended school during current school year"
label variable hv121_07 "Member attended school during current school year"
label variable hv121_08 "Member attended school during current school year"
label variable hv121_09 "Member attended school during current school year"
label variable hv121_10 "Member attended school during current school year"
label variable hv121_11 "Member attended school during current school year"
label variable hv122_01 "Educational level during current school year"
label variable hv122_02 "Educational level during current school year"
label variable hv122_03 "Educational level during current school year"
label variable hv122_04 "Educational level during current school year"
label variable hv122_05 "Educational level during current school year"
label variable hv122_06 "Educational level during current school year"
label variable hv122_07 "Educational level during current school year"
label variable hv122_08 "Educational level during current school year"
label variable hv122_09 "Educational level during current school year"
label variable hv122_10 "Educational level during current school year"
label variable hv122_11 "Educational level during current school year"
label variable hv123_01 "Grade of education during current school year"
label variable hv123_02 "Grade of education during current school year"
label variable hv123_03 "Grade of education during current school year"
label variable hv123_04 "Grade of education during current school year"
label variable hv123_05 "Grade of education during current school year"
label variable hv123_06 "Grade of education during current school year"
label variable hv123_07 "Grade of education during current school year"
label variable hv123_08 "Grade of education during current school year"
label variable hv123_09 "Grade of education during current school year"
label variable hv123_10 "Grade of education during current school year"
label variable hv123_11 "Grade of education during current school year"
label variable hv124_01 "Education in single years - current school year"
label variable hv124_02 "Education in single years - current school year"
label variable hv124_03 "Education in single years - current school year"
label variable hv124_04 "Education in single years - current school year"
label variable hv124_05 "Education in single years - current school year"
label variable hv124_06 "Education in single years - current school year"
label variable hv124_07 "Education in single years - current school year"
label variable hv124_08 "Education in single years - current school year"
label variable hv124_09 "Education in single years - current school year"
label variable hv124_10 "Education in single years - current school year"
label variable hv124_11 "Education in single years - current school year"
label variable hv125_01 "NA - Member attended school during previous school year"
label variable hv125_02 "NA - Member attended school during previous school year"
label variable hv125_03 "NA - Member attended school during previous school year"
label variable hv125_04 "NA - Member attended school during previous school year"
label variable hv125_05 "NA - Member attended school during previous school year"
label variable hv125_06 "NA - Member attended school during previous school year"
label variable hv125_07 "NA - Member attended school during previous school year"
label variable hv125_08 "NA - Member attended school during previous school year"
label variable hv125_09 "NA - Member attended school during previous school year"
label variable hv125_10 "NA - Member attended school during previous school year"
label variable hv125_11 "NA - Member attended school during previous school year"
label variable hv126_01 "NA - Educational level during previous school year"
label variable hv126_02 "NA - Educational level during previous school year"
label variable hv126_03 "NA - Educational level during previous school year"
label variable hv126_04 "NA - Educational level during previous school year"
label variable hv126_05 "NA - Educational level during previous school year"
label variable hv126_06 "NA - Educational level during previous school year"
label variable hv126_07 "NA - Educational level during previous school year"
label variable hv126_08 "NA - Educational level during previous school year"
label variable hv126_09 "NA - Educational level during previous school year"
label variable hv126_10 "NA - Educational level during previous school year"
label variable hv126_11 "NA - Educational level during previous school year"
label variable hv127_01 "NA - Grade of education during previous school year"
label variable hv127_02 "NA - Grade of education during previous school year"
label variable hv127_03 "NA - Grade of education during previous school year"
label variable hv127_04 "NA - Grade of education during previous school year"
label variable hv127_05 "NA - Grade of education during previous school year"
label variable hv127_06 "NA - Grade of education during previous school year"
label variable hv127_07 "NA - Grade of education during previous school year"
label variable hv127_08 "NA - Grade of education during previous school year"
label variable hv127_09 "NA - Grade of education during previous school year"
label variable hv127_10 "NA - Grade of education during previous school year"
label variable hv127_11 "NA - Grade of education during previous school year"
label variable hv128_01 "NA - Education in single years - previous school year"
label variable hv128_02 "NA - Education in single years - previous school year"
label variable hv128_03 "NA - Education in single years - previous school year"
label variable hv128_04 "NA - Education in single years - previous school year"
label variable hv128_05 "NA - Education in single years - previous school year"
label variable hv128_06 "NA - Education in single years - previous school year"
label variable hv128_07 "NA - Education in single years - previous school year"
label variable hv128_08 "NA - Education in single years - previous school year"
label variable hv128_09 "NA - Education in single years - previous school year"
label variable hv128_10 "NA - Education in single years - previous school year"
label variable hv128_11 "NA - Education in single years - previous school year"
label variable hv129_01 "NA - School attendance status"
label variable hv129_02 "NA - School attendance status"
label variable hv129_03 "NA - School attendance status"
label variable hv129_04 "NA - School attendance status"
label variable hv129_05 "NA - School attendance status"
label variable hv129_06 "NA - School attendance status"
label variable hv129_07 "NA - School attendance status"
label variable hv129_08 "NA - School attendance status"
label variable hv129_09 "NA - School attendance status"
label variable hv129_10 "NA - School attendance status"
label variable hv129_11 "NA - School attendance status"
label variable hv140_01 "Member has a birth certificate"
label variable hv140_02 "Member has a birth certificate"
label variable hv140_03 "Member has a birth certificate"
label variable hv140_04 "Member has a birth certificate"
label variable hv140_05 "Member has a birth certificate"
label variable hv140_06 "Member has a birth certificate"
label variable hv140_07 "Member has a birth certificate"
label variable hv140_08 "Member has a birth certificate"
label variable hv140_09 "Member has a birth certificate"
label variable hv140_10 "Member has a birth certificate"
label variable hv140_11 "Member has a birth certificate"
label variable idxh4_01 "Index to Household Schedule"
label variable idxh4_02 "Index to Household Schedule"
label variable idxh4_03 "Index to Household Schedule"
label variable idxh4_04 "Index to Household Schedule"
label variable idxh4_05 "Index to Household Schedule"
label variable idxh4_06 "Index to Household Schedule"
label variable idxh4_07 "Index to Household Schedule"
label variable idxh4_08 "Index to Household Schedule"
label variable idxh4_09 "Index to Household Schedule"
label variable idxh4_10 "Index to Household Schedule"
label variable idxh4_11 "Index to Household Schedule"
label variable sb105a_01 "Clothes on"
label variable sb105a_02 "Clothes on"
label variable sb105a_03 "Clothes on"
label variable sb105a_04 "Clothes on"
label variable sb105a_05 "Clothes on"
label variable sb105a_06 "Clothes on"
label variable sb105a_07 "Clothes on"
label variable sb105a_08 "Clothes on"
label variable sb105a_09 "Clothes on"
label variable sb105a_10 "Clothes on"
label variable sb105a_11 "Clothes on"
label variable sb205a_01 "Clothes on"
label variable sb205a_02 "Clothes on"
label variable sb205a_03 "Clothes on"
label variable sb205a_04 "Clothes on"
label variable sb205a_05 "Clothes on"
label variable sb205a_06 "Clothes on"
label variable sb205a_07 "Clothes on"
label variable sb205a_08 "Clothes on"
label variable sb205a_09 "Clothes on"
label variable sb205a_10 "Clothes on"
label variable sb205a_11 "Clothes on"
label variable sh16a_01 "Total years of schooling"
label variable sh16a_02 "Total years of schooling"
label variable sh16a_03 "Total years of schooling"
label variable sh16a_04 "Total years of schooling"
label variable sh16a_05 "Total years of schooling"
label variable sh16a_06 "Total years of schooling"
label variable sh16a_07 "Total years of schooling"
label variable sh16a_08 "Total years of schooling"
label variable sh16a_09 "Total years of schooling"
label variable sh16a_10 "Total years of schooling"
label variable sh16a_11 "Total years of schooling"
label variable sh17_01  "Highest educational level (for report)"
label variable sh17_02  "Highest educational level (for report)"
label variable sh17_03  "Highest educational level (for report)"
label variable sh17_04  "Highest educational level (for report)"
label variable sh17_05  "Highest educational level (for report)"
label variable sh17_06  "Highest educational level (for report)"
label variable sh17_07  "Highest educational level (for report)"
label variable sh17_08  "Highest educational level (for report)"
label variable sh17_09  "Highest educational level (for report)"
label variable sh17_10  "Highest educational level (for report)"
label variable sh17_11  "Highest educational level (for report)"
label variable sh17a_01 "Highest level of education attended"
label variable sh17a_02 "Highest level of education attended"
label variable sh17a_03 "Highest level of education attended"
label variable sh17a_04 "Highest level of education attended"
label variable sh17a_05 "Highest level of education attended"
label variable sh17a_06 "Highest level of education attended"
label variable sh17a_07 "Highest level of education attended"
label variable sh17a_08 "Highest level of education attended"
label variable sh17a_09 "Highest level of education attended"
label variable sh17a_10 "Highest level of education attended"
label variable sh17a_11 "Highest level of education attended"
label variable sh17b_01 "NA - Highest grade completed"
label variable sh17b_02 "NA - Highest grade completed"
label variable sh17b_03 "NA - Highest grade completed"
label variable sh17b_04 "NA - Highest grade completed"
label variable sh17b_05 "NA - Highest grade completed"
label variable sh17b_06 "NA - Highest grade completed"
label variable sh17b_07 "NA - Highest grade completed"
label variable sh17b_08 "NA - Highest grade completed"
label variable sh17b_09 "NA - Highest grade completed"
label variable sh17b_10 "NA - Highest grade completed"
label variable sh17b_11 "NA - Highest grade completed"
label variable sh17c_01 "Received an attestat for completing secondary school"
label variable sh17c_02 "Received an attestat for completing secondary school"
label variable sh17c_03 "Received an attestat for completing secondary school"
label variable sh17c_04 "Received an attestat for completing secondary school"
label variable sh17c_05 "Received an attestat for completing secondary school"
label variable sh17c_06 "Received an attestat for completing secondary school"
label variable sh17c_07 "Received an attestat for completing secondary school"
label variable sh17c_08 "Received an attestat for completing secondary school"
label variable sh17c_09 "Received an attestat for completing secondary school"
label variable sh17c_10 "Received an attestat for completing secondary school"
label variable sh17c_11 "Received an attestat for completing secondary school"
label variable ha0_1    "Index to Household Schedule"
label variable ha0_2    "Index to Household Schedule"
label variable ha0_3    "Index to Household Schedule"
label variable ha0_4    "Index to Household Schedule"
label variable ha1_1    "Woman's age in years"
label variable ha1_2    "Woman's age in years"
label variable ha1_3    "Woman's age in years"
label variable ha1_4    "Woman's age in years"
label variable ha2_1    "Woman's weight in kilograms (1 decimal)"
label variable ha2_2    "Woman's weight in kilograms (1 decimal)"
label variable ha2_3    "Woman's weight in kilograms (1 decimal)"
label variable ha2_4    "Woman's weight in kilograms (1 decimal)"
label variable ha3_1    "Woman's height in centimeters (1 decimal)"
label variable ha3_2    "Woman's height in centimeters (1 decimal)"
label variable ha3_3    "Woman's height in centimeters (1 decimal)"
label variable ha3_4    "Woman's height in centimeters (1 decimal)"
label variable ha4_1    "Height/Age percentile"
label variable ha4_2    "Height/Age percentile"
label variable ha4_3    "Height/Age percentile"
label variable ha4_4    "Height/Age percentile"
label variable ha5_1    "Height/Age standard deviation"
label variable ha5_2    "Height/Age standard deviation"
label variable ha5_3    "Height/Age standard deviation"
label variable ha5_4    "Height/Age standard deviation"
label variable ha6_1    "Height/Age percent ref. median"
label variable ha6_2    "Height/Age percent ref. median"
label variable ha6_3    "Height/Age percent ref. median"
label variable ha6_4    "Height/Age percent ref. median"
label variable ha11_1   "Weight/Height standard deviation (DHS)"
label variable ha11_2   "Weight/Height standard deviation (DHS)"
label variable ha11_3   "Weight/Height standard deviation (DHS)"
label variable ha11_4   "Weight/Height standard deviation (DHS)"
label variable ha12_1   "Weight/Height percent ref. median (DHS)"
label variable ha12_2   "Weight/Height percent ref. median (DHS)"
label variable ha12_3   "Weight/Height percent ref. median (DHS)"
label variable ha12_4   "Weight/Height percent ref. median (DHS)"
label variable ha12a_1  "Weight/Height percent ref. median (Fog)"
label variable ha12a_2  "Weight/Height percent ref. median (Fog)"
label variable ha12a_3  "Weight/Height percent ref. median (Fog)"
label variable ha12a_4  "Weight/Height percent ref. median (Fog)"
label variable ha12b_1  "Weight/Height percent ref. median (WHO)"
label variable ha12b_2  "Weight/Height percent ref. median (WHO)"
label variable ha12b_3  "Weight/Height percent ref. median (WHO)"
label variable ha12b_4  "Weight/Height percent ref. median (WHO)"
label variable ha13_1   "Result of measurement - height/weight"
label variable ha13_2   "Result of measurement - height/weight"
label variable ha13_3   "Result of measurement - height/weight"
label variable ha13_4   "Result of measurement - height/weight"
label variable ha21_1   "Fieldworker measurer code"
label variable ha21_2   "Fieldworker measurer code"
label variable ha21_3   "Fieldworker measurer code"
label variable ha21_4   "Fieldworker measurer code"
label variable ha32_1   "Date of birth (CMC)"
label variable ha32_2   "Date of birth (CMC)"
label variable ha32_3   "Date of birth (CMC)"
label variable ha32_4   "Date of birth (CMC)"
label variable ha33_1   "Completeness of HA32 information"
label variable ha33_2   "Completeness of HA32 information"
label variable ha33_3   "Completeness of HA32 information"
label variable ha33_4   "Completeness of HA32 information"
label variable ha35_1   "Smoking (cigarettes in last 24 hours)"
label variable ha35_2   "Smoking (cigarettes in last 24 hours)"
label variable ha35_3   "Smoking (cigarettes in last 24 hours)"
label variable ha35_4   "Smoking (cigarettes in last 24 hours)"
label variable ha40_1   "Body Mass Index"
label variable ha40_2   "Body Mass Index"
label variable ha40_3   "Body Mass Index"
label variable ha40_4   "Body Mass Index"
label variable ha41_1   "Rohrer's index"
label variable ha41_2   "Rohrer's index"
label variable ha41_3   "Rohrer's index"
label variable ha41_4   "Rohrer's index"
label variable ha50_1   "Under age 18"
label variable ha50_2   "Under age 18"
label variable ha50_3   "Under age 18"
label variable ha50_4   "Under age 18"
label variable ha51_1   "Line number of parent/caretaker"
label variable ha51_2   "Line number of parent/caretaker"
label variable ha51_3   "Line number of parent/caretaker"
label variable ha51_4   "Line number of parent/caretaker"
label variable ha52_1   "Read consent statement - hemoglobin"
label variable ha52_2   "Read consent statement - hemoglobin"
label variable ha52_3   "Read consent statement - hemoglobin"
label variable ha52_4   "Read consent statement - hemoglobin"
label variable ha53_1   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_2   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_3   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_4   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha54_1   "Currently pregnant"
label variable ha54_2   "Currently pregnant"
label variable ha54_3   "Currently pregnant"
label variable ha54_4   "Currently pregnant"
label variable ha55_1   "Result of measurement - hemoglobin"
label variable ha55_2   "Result of measurement - hemoglobin"
label variable ha55_3   "Result of measurement - hemoglobin"
label variable ha55_4   "Result of measurement - hemoglobin"
label variable ha56_1   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_2   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_3   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_4   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha57_1   "Anemia level"
label variable ha57_2   "Anemia level"
label variable ha57_3   "Anemia level"
label variable ha57_4   "Anemia level"
label variable ha58_1   "NA - Agrees to referral - anemia"
label variable ha58_2   "NA - Agrees to referral - anemia"
label variable ha58_3   "NA - Agrees to referral - anemia"
label variable ha58_4   "NA - Agrees to referral - anemia"
label variable ha60_1   "Marital status"
label variable ha60_2   "Marital status"
label variable ha60_3   "Marital status"
label variable ha60_4   "Marital status"
label variable ha61_1   "NA - Read consent statement - HIV"
label variable ha61_2   "NA - Read consent statement - HIV"
label variable ha61_3   "NA - Read consent statement - HIV"
label variable ha61_4   "NA - Read consent statement - HIV"
label variable ha62_1   "Bar code for HIV blood sample"
label variable ha62_2   "Bar code for HIV blood sample"
label variable ha62_3   "Bar code for HIV blood sample"
label variable ha62_4   "Bar code for HIV blood sample"
label variable ha63_1   "NA - Result of measurement - HIV"
label variable ha63_2   "NA - Result of measurement - HIV"
label variable ha63_3   "NA - Result of measurement - HIV"
label variable ha63_4   "NA - Result of measurement - HIV"
label variable ha64_1   "NA - Consent for additional tests"
label variable ha64_2   "NA - Consent for additional tests"
label variable ha64_3   "NA - Consent for additional tests"
label variable ha64_4   "NA - Consent for additional tests"
label variable ha65_1   "Result of woman's individual interview"
label variable ha65_2   "Result of woman's individual interview"
label variable ha65_3   "Result of woman's individual interview"
label variable ha65_4   "Result of woman's individual interview"
label variable ha66_1   "Woman's highest educational level"
label variable ha66_2   "Woman's highest educational level"
label variable ha66_3   "Woman's highest educational level"
label variable ha66_4   "Woman's highest educational level"
label variable ha67_1   "Woman's highest year of education"
label variable ha67_2   "Woman's highest year of education"
label variable ha67_3   "Woman's highest year of education"
label variable ha67_4   "Woman's highest year of education"
label variable ha68_1   "Woman's highest educational level (for preliminary and final report)"
label variable ha68_2   "Woman's highest educational level (for preliminary and final report)"
label variable ha68_3   "Woman's highest educational level (for preliminary and final report)"
label variable ha68_4   "Woman's highest educational level (for preliminary and final report)"
label variable ha69_1   "NA - HIV weight (6 decimals)"
label variable ha69_2   "NA - HIV weight (6 decimals)"
label variable ha69_3   "NA - HIV weight (6 decimals)"
label variable ha69_4   "NA - HIV weight (6 decimals)"
label variable ha70_1   "NA - Interviewer that took blood for HIV testing"
label variable ha70_2   "NA - Interviewer that took blood for HIV testing"
label variable ha70_3   "NA - Interviewer that took blood for HIV testing"
label variable ha70_4   "NA - Interviewer that took blood for HIV testing"
label variable hc0_1    "Index to Household Schedule"
label variable hc0_2    "Index to Household Schedule"
label variable hc0_3    "Index to Household Schedule"
label variable hc0_4    "Index to Household Schedule"
label variable hc1_1    "Child's age in months"
label variable hc1_2    "Child's age in months"
label variable hc1_3    "Child's age in months"
label variable hc1_4    "Child's age in months"
label variable hc1a_1   "Child's age in days"
label variable hc1a_2   "Child's age in days"
label variable hc1a_3   "Child's age in days"
label variable hc1a_4   "Child's age in days"
label variable hc2_1    "Child's weight in kilograms (1 decimal)"
label variable hc2_2    "Child's weight in kilograms (1 decimal)"
label variable hc2_3    "Child's weight in kilograms (1 decimal)"
label variable hc2_4    "Child's weight in kilograms (1 decimal)"
label variable hc3_1    "Child's height in centimeters (1 decimal)"
label variable hc3_2    "Child's height in centimeters (1 decimal)"
label variable hc3_3    "Child's height in centimeters (1 decimal)"
label variable hc3_4    "Child's height in centimeters (1 decimal)"
label variable hc4_1    "Height/Age percentile"
label variable hc4_2    "Height/Age percentile"
label variable hc4_3    "Height/Age percentile"
label variable hc4_4    "Height/Age percentile"
label variable hc5_1    "Height/Age standard deviation"
label variable hc5_2    "Height/Age standard deviation"
label variable hc5_3    "Height/Age standard deviation"
label variable hc5_4    "Height/Age standard deviation"
label variable hc6_1    "Height/Age percent of ref. median"
label variable hc6_2    "Height/Age percent of ref. median"
label variable hc6_3    "Height/Age percent of ref. median"
label variable hc6_4    "Height/Age percent of ref. median"
label variable hc7_1    "Weight/Age percentile"
label variable hc7_2    "Weight/Age percentile"
label variable hc7_3    "Weight/Age percentile"
label variable hc7_4    "Weight/Age percentile"
label variable hc8_1    "Weight/Age standard deviation"
label variable hc8_2    "Weight/Age standard deviation"
label variable hc8_3    "Weight/Age standard deviation"
label variable hc8_4    "Weight/Age standard deviation"
label variable hc9_1    "Weight/Age percent of ref. median"
label variable hc9_2    "Weight/Age percent of ref. median"
label variable hc9_3    "Weight/Age percent of ref. median"
label variable hc9_4    "Weight/Age percent of ref. median"
label variable hc10_1   "Weight/Height percentile"
label variable hc10_2   "Weight/Height percentile"
label variable hc10_3   "Weight/Height percentile"
label variable hc10_4   "Weight/Height percentile"
label variable hc11_1   "Weight/Height standard deviation"
label variable hc11_2   "Weight/Height standard deviation"
label variable hc11_3   "Weight/Height standard deviation"
label variable hc11_4   "Weight/Height standard deviation"
label variable hc12_1   "Weight/Height percent of ref. median"
label variable hc12_2   "Weight/Height percent of ref. median"
label variable hc12_3   "Weight/Height percent of ref. median"
label variable hc12_4   "Weight/Height percent of ref. median"
label variable hc13_1   "Result of measurement - height/weight"
label variable hc13_2   "Result of measurement - height/weight"
label variable hc13_3   "Result of measurement - height/weight"
label variable hc13_4   "Result of measurement - height/weight"
label variable hc15_1   "Height: lying or standing"
label variable hc15_2   "Height: lying or standing"
label variable hc15_3   "Height: lying or standing"
label variable hc15_4   "Height: lying or standing"
label variable hc16_1   "Day of birth"
label variable hc16_2   "Day of birth"
label variable hc16_3   "Day of birth"
label variable hc16_4   "Day of birth"
label variable hc17_1   "Date measured (day)"
label variable hc17_2   "Date measured (day)"
label variable hc17_3   "Date measured (day)"
label variable hc17_4   "Date measured (day)"
label variable hc18_1   "Date measured (month)"
label variable hc18_2   "Date measured (month)"
label variable hc18_3   "Date measured (month)"
label variable hc18_4   "Date measured (month)"
label variable hc19_1   "Date measured (year)"
label variable hc19_2   "Date measured (year)"
label variable hc19_3   "Date measured (year)"
label variable hc19_4   "Date measured (year)"
label variable hc20_1   "Century Day Code (CDC) of measurement"
label variable hc20_2   "Century Day Code (CDC) of measurement"
label variable hc20_3   "Century Day Code (CDC) of measurement"
label variable hc20_4   "Century Day Code (CDC) of measurement"
label variable hc21_1   "Fieldworker measurer code"
label variable hc21_2   "Fieldworker measurer code"
label variable hc21_3   "Fieldworker measurer code"
label variable hc21_4   "Fieldworker measurer code"
label variable hc27_1   "Sex"
label variable hc27_2   "Sex"
label variable hc27_3   "Sex"
label variable hc27_4   "Sex"
label variable hc30_1   "Month of birth"
label variable hc30_2   "Month of birth"
label variable hc30_3   "Month of birth"
label variable hc30_4   "Month of birth"
label variable hc31_1   "Year of birth"
label variable hc31_2   "Year of birth"
label variable hc31_3   "Year of birth"
label variable hc31_4   "Year of birth"
label variable hc32_1   "Date of birth (CMC)"
label variable hc32_2   "Date of birth (CMC)"
label variable hc32_3   "Date of birth (CMC)"
label variable hc32_4   "Date of birth (CMC)"
label variable hc32a_1  "Century Day Code (CDC) of birth"
label variable hc32a_2  "Century Day Code (CDC) of birth"
label variable hc32a_3  "Century Day Code (CDC) of birth"
label variable hc32a_4  "Century Day Code (CDC) of birth"
label variable hc33_1   "Completeness of HC32 information"
label variable hc33_2   "Completeness of HC32 information"
label variable hc33_3   "Completeness of HC32 information"
label variable hc33_4   "Completeness of HC32 information"
label variable hc51_1   "Line number of parent/caretaker"
label variable hc51_2   "Line number of parent/caretaker"
label variable hc51_3   "Line number of parent/caretaker"
label variable hc51_4   "Line number of parent/caretaker"
label variable hc52_1   "Read consent statement - hemoglobin"
label variable hc52_2   "Read consent statement - hemoglobin"
label variable hc52_3   "Read consent statement - hemoglobin"
label variable hc52_4   "Read consent statement - hemoglobin"
label variable hc53_1   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_2   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_3   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_4   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55_1   "Result of measurement - hemoglobin"
label variable hc55_2   "Result of measurement - hemoglobin"
label variable hc55_3   "Result of measurement - hemoglobin"
label variable hc55_4   "Result of measurement - hemoglobin"
label variable hc56_1   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_2   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_3   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_4   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57_1   "Anemia level"
label variable hc57_2   "Anemia level"
label variable hc57_3   "Anemia level"
label variable hc57_4   "Anemia level"
label variable hc58_1   "NA - Agrees to referral - anemia"
label variable hc58_2   "NA - Agrees to referral - anemia"
label variable hc58_3   "NA - Agrees to referral - anemia"
label variable hc58_4   "NA - Agrees to referral - anemia"
label variable hc60_1   "Mother's line number (woman's questionnaire)"
label variable hc60_2   "Mother's line number (woman's questionnaire)"
label variable hc60_3   "Mother's line number (woman's questionnaire)"
label variable hc60_4   "Mother's line number (woman's questionnaire)"
label variable hc61_1   "Mother's highest educational level"
label variable hc61_2   "Mother's highest educational level"
label variable hc61_3   "Mother's highest educational level"
label variable hc61_4   "Mother's highest educational level"
label variable hc62_1   "Mother's highest year of education"
label variable hc62_2   "Mother's highest year of education"
label variable hc62_3   "Mother's highest year of education"
label variable hc62_4   "Mother's highest year of education"
label variable hc63_1   "Preceding birth interval (months)"
label variable hc63_2   "Preceding birth interval (months)"
label variable hc63_3   "Preceding birth interval (months)"
label variable hc63_4   "Preceding birth interval (months)"
label variable hc64_1   "Birth order number"
label variable hc64_2   "Birth order number"
label variable hc64_3   "Birth order number"
label variable hc64_4   "Birth order number"
label variable hc68_1   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_2   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_3   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_4   "Mother's highest educational level (for preliminary and final report)"
label variable hc70_1   "Height/Age standard deviation (new WHO)"
label variable hc70_2   "Height/Age standard deviation (new WHO)"
label variable hc70_3   "Height/Age standard deviation (new WHO)"
label variable hc70_4   "Height/Age standard deviation (new WHO)"
label variable hc71_1   "Weight/Age standard deviation (new WHO)"
label variable hc71_2   "Weight/Age standard deviation (new WHO)"
label variable hc71_3   "Weight/Age standard deviation (new WHO)"
label variable hc71_4   "Weight/Age standard deviation (new WHO)"
label variable hc72_1   "Weight/Height standard deviation (new WHO)"
label variable hc72_2   "Weight/Height standard deviation (new WHO)"
label variable hc72_3   "Weight/Height standard deviation (new WHO)"
label variable hc72_4   "Weight/Height standard deviation (new WHO)"
label variable hc73_1   "BMI standard deviation (new WHO)"
label variable hc73_2   "BMI standard deviation (new WHO)"
label variable hc73_3   "BMI standard deviation (new WHO)"
label variable hc73_4   "BMI standard deviation (new WHO)"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV018   
 99999 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV022   
     1 "Yerevan - Urban"
     2 "Aragatsotn - Urban"
     3 "Aragatsotn - Rural"
     4 "Ararat - Urban"
     5 "Ararat - Rural"
     6 "Armavir - Urban"
     7 "Armavir - Rural"
     8 "Gegharkunik - Urban"
     9 "Gegharkunik - Rural"
    10 "Lori - Urban"
    11 "Lori - Rural"
    12 "Kotayk - Urban"
    13 "Kotayk - Rural"
    14 "Shirak - Urban"
    15 "Shirak - Rural"
    16 "Syunik - Urban"
    17 "Syunik - Rural"
    18 "Vayots Dzor - Urban"
    19 "Vayots Dzor - Rural"
    20 "Tavush - Urban"
    21 "Tavush - Rural"
;
label define HV023   
     0 "National"
     1 "Yerevan"
     2 "Aragatsotn - Urban"
     3 "Aragatsotn - Rural"
     4 "Ararat- Urban"
     5 "Ararat- Rural"
     6 "Armavir - Urban"
     7 "Armavir - Rural"
     8 "Gegharkunik - Urban"
     9 "Gegharkunik - Rural"
    10 "Lori- Urban"
    11 "Lori - Rural"
    12 "Kotayk - Urban"
    13 "Kotayk - Rural"
    14 "Shirak - Urban"
    15 "Shirak - Rural"
    16 "Syunik - Urban"
    17 "Syunik - Rural"
    18 "Vayots Dzor - Urban"
    19 "Vayots Dzor - Rural"
    20 "Tavush - Urban"
    21 "Tavush - Rural"
;
label define HV024   
     1 "Yerevan"
     2 "Aragatsotn"
     3 "Ararat"
     4 "Armavir"
     5 "Gegharkunik"
     6 "Lori"
     7 "Kotayk"
     8 "Shirak"
     9 "Syunik"
    10 "Vayots Dzor"
    11 "Tavush"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV030   
 99999 "Missing"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV045A  
     0 "English"
     1 "Armenian"
     2 "Russian"
     3 "Other"
;
label define HV045B  
     0 "English"
     1 "Armenian"
     2 "Russian"
     3 "Other"
;
label define HV045C  
     0 "English"
     1 "Armenian"
     2 "Russian"
     3 "Other"
;
label define HV046   
     0 "No"
     1 "Yes"
;
label define HV801   
  9999 "Missing"
;
label define HV802   
  9999 "Missing"
;
label define HV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define HV804   
     9 "Missing"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV201A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    11 "Natural floor - Earth/sand"
    21 "Rudimentary floor - Wood planks"
    31 "Finished Floor - Parquet or polished wood or laminate"
    32 "Finished Floor - Vinyl or linoleum"
    33 "Finished Floor - Ceramic or marble tiles"
    34 "Finished Floor - Cement"
    35 "Finished Floor - Carpeted"
    96 "Other"
;
label define HV214   
    11 "No walls"
    12 "Tree trunks"
    13 "Dirt"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    31 "Cement/monolit"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks or panels"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
;
label define HV215   
    11 "No roof"
    13 "Sod"
    21 "Rustic mat"
    23 "Wood planks"
    24 "Cardboard"
    31 "Metal"
    32 "Wood"
    33 "Calamine/cement fiber"
    34 "Ceramic tiles"
    35 "Cement"
    36 "Roofing shingles/shifer"
    37 "Taule"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in house"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV230A  
     1 "Observed, fixed place"
     2 "Observed, mobile place"
     3 "Not observed: not in dwelling"
     4 "Not observed: no permission to see"
     5 "Not observed: other reason"
;
label define HV230B  
     0 "Water not available"
     1 "Water is available"
;
label define HV232   
     0 "No"
     1 "Yes"
;
label define HV232B  
     0 "No"
     1 "Yes"
;
label define HV232C  
     0 "No"
     1 "Yes"
;
label define HV232D  
     0 "No"
     1 "Yes"
;
label define HV232E  
     0 "No"
     1 "Yes"
;
label define HV232Y  
     0 "No"
     1 "Yes: no cleansing agent observed"
;
label define HV234   
     0 "0 PPM (no iodine)"
     7 "Below 15 PPM"
    15 "15 PPM and above"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define HV234A  
     0 "No iodine"
     1 "Iodine present"
     3 "No salt in household"
     6 "Salt not tested"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV236   
     1 "Adult woman"
     2 "Adult man"
     3 "Female child under 15 years old"
     4 "Male child under 15 years old"
     6 "Other"
;
label define HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237I  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237J  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237K  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237Z  
     0 "No"
     1 "Yes: don't know what is done to water"
     8 "Don't know"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV238A  
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     0 "Neither chimney or hood"
     1 "Chimney"
     2 "Hood"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV243E  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
   950 "95 or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV252   
     0 "Never"
     1 "Daily"
     2 "Weekly"
     3 "Monthly"
     4 "Less than once a month"
;
label define HV253   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253Z  
     0 "No"
     1 "Yes: don't know who sprayed the dwelling"
     8 "Don't know if it was sprayed"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HV270A  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SH121G  
     0 "No"
     1 "Yes"
;
label define SH121H  
     0 "No"
     1 "Yes"
;
label define SH121I  
     0 "No"
     1 "Yes"
;
label define SH121J  
     0 "No"
     1 "Yes"
;
label define SH121K  
     0 "No"
     1 "Yes"
;
label define SH121L  
     0 "No"
     1 "Yes"
;
label define SH121M  
     0 "No"
     1 "Yes"
;
label define SH121N  
     0 "No"
     1 "Yes"
;
label define SH121O  
     0 "No"
     1 "Yes"
;
label define SH121P  
     0 "No"
     1 "Yes"
;
label define SH121Q  
     0 "No"
     1 "Yes"
;
label define SH121R  
     0 "No"
     1 "Yes"
;
label define SH121S  
     0 "No"
     1 "Yes"
;
label define SH121T  
     0 "No"
     1 "Yes"
;
label define SH121U  
     0 "No"
     1 "Yes"
;
label define SH125A  
     0 "No"
     1 "Yes"
;
label define SH125B  
     0 "No"
     1 "Yes"
;
label define SH125C  
     0 "No"
     1 "Yes"
;
label define SH127   
     0 "No"
     1 "Yes"
;
label define SH128M  
     1 "Walking"
     2 "By car or taxi"
     3 "By public transportation"
;
label define SH128N  
   995 "995+"
   997 "Inconsistent"
   998 "Don't know"
;
label define SH43A   
     0 "No"
     1 "Yes"
;
label define SH43B   
     0 "No"
     1 "Yes"
;
label define SH43C   
     0 "No"
     1 "Yes"
;
label define SH43D   
     0 "No"
     1 "Yes"
;
label define SH43E   
     0 "No"
     1 "Yes"
;
label define SH43F   
     0 "No"
     1 "Yes"
;
label define SH43G   
     0 "No"
     1 "Yes"
;
label define SH43H   
     0 "No"
     1 "Yes"
;
label define SH43I   
     0 "No"
     1 "Yes"
;
label define SH43J   
     0 "No"
     1 "Yes"
;
label define SH43K   
     0 "No"
     1 "Yes"
;
label define SH44    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH120   
999950 "More than 950,000"
999998 "Unknown"
999999 "Missing"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    98 "Don't know"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV106   
     0 "No education"
     1 "Basic"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV107   
    98 "Don't know"
;
label define HV108   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
;
label define HV110   
     0 "No"
     1 "Yes"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV112   
     0 "Mother not in household"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV114   
     0 "Father not in household"
;
label define HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever married"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV123   
    98 "Don't know"
;
label define HV124   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV127   
    98 "Don't know"
;
label define HV128   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "Don't know"
;
label define HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     8 "Don't know"
;
label define SB105A  
     1 "Yes"
     0 "No"
;
label define SB205A  
     1 "Yes"
     0 "No"
;
label define SH16A   
    98 "Don't know"
;
label define SH17    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Secondary special"
     4 "Higher"
     8 "Don't know"
;
label define SH17A   
     0 "Preschool"
     1 "Primary-Basic-Secondary"
     2 "Secondary special"
     3 "Higher"
     8 "Don't know"
;
label define SH17B   
     0 "< 1 year completed"
    98 "Don't know"
;
label define SH17C   
     1 "Yes"
     0 "No"
;
label define HA2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA4     
  9998 "Flagged cases"
;
label define HA5     
  9998 "Flagged cases"
;
label define HA6     
 99998 "Flagged cases"
;
label define HA11    
  9998 "Flagged cases"
;
label define HA12    
 99998 "Flagged cases"
;
label define HA12A   
 99998 "Flagged cases"
;
label define HA12B   
 99998 "Flagged cases"
;
label define HA13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA33    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HA35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
;
label define HA40    
  9998 "Flagged cases"
;
label define HA41    
  9998 "Flagged cases"
;
label define HA50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HA51    
     0 "Not in household"
;
label define HA52    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define HA53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HA54    
     0 "No/don't know"
     1 "Yes"
;
label define HA55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA56    
   997 "Inconsistent"
   994 "Not Present"
   995 "Refused"
   996 "Other"
;
label define HA57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HA58    
     0 "No"
     1 "Yes"
;
label define HA60    
     1 "Never in union"
     2 "Other"
;
label define HA61    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
     6 "Sample not tested/lost/not enough DBS"
;
label define HA63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost/damaged/insufficient"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HA64    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     6 "Sample not tested/lost/not enough DBS"
;
label define HA65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HA66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HA67    
    98 "Don't know"
;
label define HA68    
     0 "No education"
     1 "Primary"
     2 "Basic secondary"
     3 "Secondary special"
     4 "Higher"
     8 "Don't know"
;
label define HC2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC4     
  9998 "Flagged cases"
;
label define HC5     
  9998 "Flagged cases"
;
label define HC6     
 99998 "Flagged cases"
;
label define HC7     
  9998 "Flagged cases"
;
label define HC8     
  9998 "Flagged cases"
;
label define HC9     
 99998 "Flagged cases"
;
label define HC10    
  9998 "Flagged cases"
;
label define HC11    
  9998 "Flagged cases"
;
label define HC12    
 99998 "Flagged cases"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC15    
     0 "Not measured"
     1 "Lying"
     2 "Standing"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present/other"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC62    
     0 "No education"
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary"
     2 "Basic secondary"
     3 "Secondary special"
     4 "Higher"
     8 "Don't know"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;

#delimit cr
label values hv003    HV003   
label values hv015    HV015   
label values hv020    HV020   
label values hv022    HV022   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv044    HV044   
label values hv045a   HV045A  
label values hv045b   HV045B  
label values hv045c   HV045C  
label values hv046    HV046   
label values hv803    HV803   
label values hv201    HV201   
label values hv202    HV202   
label values hv201a   HV201A  
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv230a   HV230A  
label values hv230b   HV230B  
label values hv232    HV232   
label values hv232b   HV232B  
label values hv232c   HV232C  
label values hv232d   HV232D  
label values hv232e   HV232E  
label values hv232y   HV232Y  
label values hv234    HV234   
label values hv234a   HV234A  
label values hv235    HV235   
label values hv236    HV236   
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237g   HV237G  
label values hv237h   HV237H  
label values hv237i   HV237I  
label values hv237j   HV237J  
label values hv237k   HV237K  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv238a   HV238A  
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv243e   HV243E  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv252    HV252   
label values hv253    HV253   
label values hv253a   HV253A  
label values hv253b   HV253B  
label values hv253c   HV253C  
label values hv253d   HV253D  
label values hv253e   HV253E  
label values hv253f   HV253F  
label values hv253g   HV253G  
label values hv253h   HV253H  
label values hv253x   HV253X  
label values hv253z   HV253Z  
label values hv270    HV270   
label values hv270a   HV270A  
label values hml1     HML1    
label values sh121g   SH121G  
label values sh121h   SH121H  
label values sh121i   SH121I  
label values sh121j   SH121J  
label values sh121k   SH121K  
label values sh121l   SH121L  
label values sh121m   SH121M  
label values sh121n   SH121N  
label values sh121o   SH121O  
label values sh121p   SH121P  
label values sh121q   SH121Q  
label values sh121r   SH121R  
label values sh121s   SH121S  
label values sh121t   SH121T  
label values sh121u   SH121U  
label values sh125a   SH125A  
label values sh125b   SH125B  
label values sh125c   SH125C  
label values sh127    SH127   
label values sh128m   SH128M  
label values sh128n   SH128N  
label values sh43a    SH43A   
label values sh43b    SH43B   
label values sh43c    SH43C   
label values sh43d    SH43D   
label values sh43e    SH43E   
label values sh43f    SH43F   
label values sh43g    SH43G   
label values sh43h    SH43H   
label values sh43i    SH43I   
label values sh43j    SH43J   
label values sh43k    SH43K   
label values sh44     SH44    
label values sh120    SH120   
label values hv101_01 HV101   
label values hv101_02 HV101   
label values hv101_03 HV101   
label values hv101_04 HV101   
label values hv101_05 HV101   
label values hv101_06 HV101   
label values hv101_07 HV101   
label values hv101_08 HV101   
label values hv101_09 HV101   
label values hv101_10 HV101   
label values hv101_11 HV101   
label values hv102_01 HV102   
label values hv102_02 HV102   
label values hv102_03 HV102   
label values hv102_04 HV102   
label values hv102_05 HV102   
label values hv102_06 HV102   
label values hv102_07 HV102   
label values hv102_08 HV102   
label values hv102_09 HV102   
label values hv102_10 HV102   
label values hv102_11 HV102   
label values hv103_01 HV103   
label values hv103_02 HV103   
label values hv103_03 HV103   
label values hv103_04 HV103   
label values hv103_05 HV103   
label values hv103_06 HV103   
label values hv103_07 HV103   
label values hv103_08 HV103   
label values hv103_09 HV103   
label values hv103_10 HV103   
label values hv103_11 HV103   
label values hv104_01 HV104   
label values hv104_02 HV104   
label values hv104_03 HV104   
label values hv104_04 HV104   
label values hv104_05 HV104   
label values hv104_06 HV104   
label values hv104_07 HV104   
label values hv104_08 HV104   
label values hv104_09 HV104   
label values hv104_10 HV104   
label values hv104_11 HV104   
label values hv105_01 HV105   
label values hv105_02 HV105   
label values hv105_03 HV105   
label values hv105_04 HV105   
label values hv105_05 HV105   
label values hv105_06 HV105   
label values hv105_07 HV105   
label values hv105_08 HV105   
label values hv105_09 HV105   
label values hv105_10 HV105   
label values hv105_11 HV105   
label values hv106_01 HV106   
label values hv106_02 HV106   
label values hv106_03 HV106   
label values hv106_04 HV106   
label values hv106_05 HV106   
label values hv106_06 HV106   
label values hv106_07 HV106   
label values hv106_08 HV106   
label values hv106_09 HV106   
label values hv106_10 HV106   
label values hv106_11 HV106   
label values hv107_01 HV107   
label values hv107_02 HV107   
label values hv107_03 HV107   
label values hv107_04 HV107   
label values hv107_05 HV107   
label values hv107_06 HV107   
label values hv107_07 HV107   
label values hv107_08 HV107   
label values hv107_09 HV107   
label values hv107_10 HV107   
label values hv107_11 HV107   
label values hv108_01 HV108   
label values hv108_02 HV108   
label values hv108_03 HV108   
label values hv108_04 HV108   
label values hv108_05 HV108   
label values hv108_06 HV108   
label values hv108_07 HV108   
label values hv108_08 HV108   
label values hv108_09 HV108   
label values hv108_10 HV108   
label values hv108_11 HV108   
label values hv109_01 HV109   
label values hv109_02 HV109   
label values hv109_03 HV109   
label values hv109_04 HV109   
label values hv109_05 HV109   
label values hv109_06 HV109   
label values hv109_07 HV109   
label values hv109_08 HV109   
label values hv109_09 HV109   
label values hv109_10 HV109   
label values hv109_11 HV109   
label values hv110_01 HV110   
label values hv110_02 HV110   
label values hv110_03 HV110   
label values hv110_04 HV110   
label values hv110_05 HV110   
label values hv110_06 HV110   
label values hv110_07 HV110   
label values hv110_08 HV110   
label values hv110_09 HV110   
label values hv110_10 HV110   
label values hv110_11 HV110   
label values hv111_01 HV111   
label values hv111_02 HV111   
label values hv111_03 HV111   
label values hv111_04 HV111   
label values hv111_05 HV111   
label values hv111_06 HV111   
label values hv111_07 HV111   
label values hv111_08 HV111   
label values hv111_09 HV111   
label values hv111_10 HV111   
label values hv111_11 HV111   
label values hv112_01 HV112   
label values hv112_02 HV112   
label values hv112_03 HV112   
label values hv112_04 HV112   
label values hv112_05 HV112   
label values hv112_06 HV112   
label values hv112_07 HV112   
label values hv112_08 HV112   
label values hv112_09 HV112   
label values hv112_10 HV112   
label values hv112_11 HV112   
label values hv113_01 HV113   
label values hv113_02 HV113   
label values hv113_03 HV113   
label values hv113_04 HV113   
label values hv113_05 HV113   
label values hv113_06 HV113   
label values hv113_07 HV113   
label values hv113_08 HV113   
label values hv113_09 HV113   
label values hv113_10 HV113   
label values hv113_11 HV113   
label values hv114_01 HV114   
label values hv114_02 HV114   
label values hv114_03 HV114   
label values hv114_04 HV114   
label values hv114_05 HV114   
label values hv114_06 HV114   
label values hv114_07 HV114   
label values hv114_08 HV114   
label values hv114_09 HV114   
label values hv114_10 HV114   
label values hv114_11 HV114   
label values hv115_01 HV115   
label values hv115_02 HV115   
label values hv115_03 HV115   
label values hv115_04 HV115   
label values hv115_05 HV115   
label values hv115_06 HV115   
label values hv115_07 HV115   
label values hv115_08 HV115   
label values hv115_09 HV115   
label values hv115_10 HV115   
label values hv115_11 HV115   
label values hv116_01 HV116   
label values hv116_02 HV116   
label values hv116_03 HV116   
label values hv116_04 HV116   
label values hv116_05 HV116   
label values hv116_06 HV116   
label values hv116_07 HV116   
label values hv116_08 HV116   
label values hv116_09 HV116   
label values hv116_10 HV116   
label values hv116_11 HV116   
label values hv117_01 HV117   
label values hv117_02 HV117   
label values hv117_03 HV117   
label values hv117_04 HV117   
label values hv117_05 HV117   
label values hv117_06 HV117   
label values hv117_07 HV117   
label values hv117_08 HV117   
label values hv117_09 HV117   
label values hv117_10 HV117   
label values hv117_11 HV117   
label values hv118_01 HV118   
label values hv118_02 HV118   
label values hv118_03 HV118   
label values hv118_04 HV118   
label values hv118_05 HV118   
label values hv118_06 HV118   
label values hv118_07 HV118   
label values hv118_08 HV118   
label values hv118_09 HV118   
label values hv118_10 HV118   
label values hv118_11 HV118   
label values hv120_01 HV120   
label values hv120_02 HV120   
label values hv120_03 HV120   
label values hv120_04 HV120   
label values hv120_05 HV120   
label values hv120_06 HV120   
label values hv120_07 HV120   
label values hv120_08 HV120   
label values hv120_09 HV120   
label values hv120_10 HV120   
label values hv120_11 HV120   
label values hv121_01 HV121   
label values hv121_02 HV121   
label values hv121_03 HV121   
label values hv121_04 HV121   
label values hv121_05 HV121   
label values hv121_06 HV121   
label values hv121_07 HV121   
label values hv121_08 HV121   
label values hv121_09 HV121   
label values hv121_10 HV121   
label values hv121_11 HV121   
label values hv122_01 HV122   
label values hv122_02 HV122   
label values hv122_03 HV122   
label values hv122_04 HV122   
label values hv122_05 HV122   
label values hv122_06 HV122   
label values hv122_07 HV122   
label values hv122_08 HV122   
label values hv122_09 HV122   
label values hv122_10 HV122   
label values hv122_11 HV122   
label values hv123_01 HV123   
label values hv123_02 HV123   
label values hv123_03 HV123   
label values hv123_04 HV123   
label values hv123_05 HV123   
label values hv123_06 HV123   
label values hv123_07 HV123   
label values hv123_08 HV123   
label values hv123_09 HV123   
label values hv123_10 HV123   
label values hv123_11 HV123   
label values hv124_01 HV124   
label values hv124_02 HV124   
label values hv124_03 HV124   
label values hv124_04 HV124   
label values hv124_05 HV124   
label values hv124_06 HV124   
label values hv124_07 HV124   
label values hv124_08 HV124   
label values hv124_09 HV124   
label values hv124_10 HV124   
label values hv124_11 HV124   
label values hv125_01 HV125   
label values hv125_02 HV125   
label values hv125_03 HV125   
label values hv125_04 HV125   
label values hv125_05 HV125   
label values hv125_06 HV125   
label values hv125_07 HV125   
label values hv125_08 HV125   
label values hv125_09 HV125   
label values hv125_10 HV125   
label values hv125_11 HV125   
label values hv126_01 HV126   
label values hv126_02 HV126   
label values hv126_03 HV126   
label values hv126_04 HV126   
label values hv126_05 HV126   
label values hv126_06 HV126   
label values hv126_07 HV126   
label values hv126_08 HV126   
label values hv126_09 HV126   
label values hv126_10 HV126   
label values hv126_11 HV126   
label values hv127_01 HV127   
label values hv127_02 HV127   
label values hv127_03 HV127   
label values hv127_04 HV127   
label values hv127_05 HV127   
label values hv127_06 HV127   
label values hv127_07 HV127   
label values hv127_08 HV127   
label values hv127_09 HV127   
label values hv127_10 HV127   
label values hv127_11 HV127   
label values hv128_01 HV128   
label values hv128_02 HV128   
label values hv128_03 HV128   
label values hv128_04 HV128   
label values hv128_05 HV128   
label values hv128_06 HV128   
label values hv128_07 HV128   
label values hv128_08 HV128   
label values hv128_09 HV128   
label values hv128_10 HV128   
label values hv128_11 HV128   
label values hv129_01 HV129   
label values hv129_02 HV129   
label values hv129_03 HV129   
label values hv129_04 HV129   
label values hv129_05 HV129   
label values hv129_06 HV129   
label values hv129_07 HV129   
label values hv129_08 HV129   
label values hv129_09 HV129   
label values hv129_10 HV129   
label values hv129_11 HV129   
label values hv140_01 HV140   
label values hv140_02 HV140   
label values hv140_03 HV140   
label values hv140_04 HV140   
label values hv140_05 HV140   
label values hv140_06 HV140   
label values hv140_07 HV140   
label values hv140_08 HV140   
label values hv140_09 HV140   
label values hv140_10 HV140   
label values hv140_11 HV140   
label values sb105a_01 SB105A  
label values sb105a_02 SB105A  
label values sb105a_03 SB105A  
label values sb105a_04 SB105A  
label values sb105a_05 SB105A  
label values sb105a_06 SB105A  
label values sb105a_07 SB105A  
label values sb105a_08 SB105A  
label values sb105a_09 SB105A  
label values sb105a_10 SB105A  
label values sb105a_11 SB105A  
label values sb205a_01 SB205A  
label values sb205a_02 SB205A  
label values sb205a_03 SB205A  
label values sb205a_04 SB205A  
label values sb205a_05 SB205A  
label values sb205a_06 SB205A  
label values sb205a_07 SB205A  
label values sb205a_08 SB205A  
label values sb205a_09 SB205A  
label values sb205a_10 SB205A  
label values sb205a_11 SB205A  
label values sh16a_01 SH16A   
label values sh16a_02 SH16A   
label values sh16a_03 SH16A   
label values sh16a_04 SH16A   
label values sh16a_05 SH16A   
label values sh16a_06 SH16A   
label values sh16a_07 SH16A   
label values sh16a_08 SH16A   
label values sh16a_09 SH16A   
label values sh16a_10 SH16A   
label values sh16a_11 SH16A   
label values sh17_01  SH17    
label values sh17_02  SH17    
label values sh17_03  SH17    
label values sh17_04  SH17    
label values sh17_05  SH17    
label values sh17_06  SH17    
label values sh17_07  SH17    
label values sh17_08  SH17    
label values sh17_09  SH17    
label values sh17_10  SH17    
label values sh17_11  SH17    
label values sh17a_01 SH17A   
label values sh17a_02 SH17A   
label values sh17a_03 SH17A   
label values sh17a_04 SH17A   
label values sh17a_05 SH17A   
label values sh17a_06 SH17A   
label values sh17a_07 SH17A   
label values sh17a_08 SH17A   
label values sh17a_09 SH17A   
label values sh17a_10 SH17A   
label values sh17a_11 SH17A   
label values sh17b_01 SH17B   
label values sh17b_02 SH17B   
label values sh17b_03 SH17B   
label values sh17b_04 SH17B   
label values sh17b_05 SH17B   
label values sh17b_06 SH17B   
label values sh17b_07 SH17B   
label values sh17b_08 SH17B   
label values sh17b_09 SH17B   
label values sh17b_10 SH17B   
label values sh17b_11 SH17B   
label values sh17c_01 SH17C   
label values sh17c_02 SH17C   
label values sh17c_03 SH17C   
label values sh17c_04 SH17C   
label values sh17c_05 SH17C   
label values sh17c_06 SH17C   
label values sh17c_07 SH17C   
label values sh17c_08 SH17C   
label values sh17c_09 SH17C   
label values sh17c_10 SH17C   
label values sh17c_11 SH17C   
label values ha2_1    HA2     
label values ha2_2    HA2     
label values ha2_3    HA2     
label values ha2_4    HA2     
label values ha3_1    HA3     
label values ha3_2    HA3     
label values ha3_3    HA3     
label values ha3_4    HA3     
label values ha4_1    HA4     
label values ha4_2    HA4     
label values ha4_3    HA4     
label values ha4_4    HA4     
label values ha5_1    HA5     
label values ha5_2    HA5     
label values ha5_3    HA5     
label values ha5_4    HA5     
label values ha6_1    HA6     
label values ha6_2    HA6     
label values ha6_3    HA6     
label values ha6_4    HA6     
label values ha11_1   HA11    
label values ha11_2   HA11    
label values ha11_3   HA11    
label values ha11_4   HA11    
label values ha12_1   HA12    
label values ha12_2   HA12    
label values ha12_3   HA12    
label values ha12_4   HA12    
label values ha12a_1  HA12A   
label values ha12a_2  HA12A   
label values ha12a_3  HA12A   
label values ha12a_4  HA12A   
label values ha12b_1  HA12B   
label values ha12b_2  HA12B   
label values ha12b_3  HA12B   
label values ha12b_4  HA12B   
label values ha13_1   HA13    
label values ha13_2   HA13    
label values ha13_3   HA13    
label values ha13_4   HA13    
label values ha33_1   HA33    
label values ha33_2   HA33    
label values ha33_3   HA33    
label values ha33_4   HA33    
label values ha35_1   HA35    
label values ha35_2   HA35    
label values ha35_3   HA35    
label values ha35_4   HA35    
label values ha40_1   HA40    
label values ha40_2   HA40    
label values ha40_3   HA40    
label values ha40_4   HA40    
label values ha41_1   HA41    
label values ha41_2   HA41    
label values ha41_3   HA41    
label values ha41_4   HA41    
label values ha50_1   HA50    
label values ha50_2   HA50    
label values ha50_3   HA50    
label values ha50_4   HA50    
label values ha51_1   HA51    
label values ha51_2   HA51    
label values ha51_3   HA51    
label values ha51_4   HA51    
label values ha52_1   HA52    
label values ha52_2   HA52    
label values ha52_3   HA52    
label values ha52_4   HA52    
label values ha53_1   HA53    
label values ha53_2   HA53    
label values ha53_3   HA53    
label values ha53_4   HA53    
label values ha54_1   HA54    
label values ha54_2   HA54    
label values ha54_3   HA54    
label values ha54_4   HA54    
label values ha55_1   HA55    
label values ha55_2   HA55    
label values ha55_3   HA55    
label values ha55_4   HA55    
label values ha56_1   HA56    
label values ha56_2   HA56    
label values ha56_3   HA56    
label values ha56_4   HA56    
label values ha57_1   HA57    
label values ha57_2   HA57    
label values ha57_3   HA57    
label values ha57_4   HA57    
label values ha58_1   HA58    
label values ha58_2   HA58    
label values ha58_3   HA58    
label values ha58_4   HA58    
label values ha60_1   HA60    
label values ha60_2   HA60    
label values ha60_3   HA60    
label values ha60_4   HA60    
label values ha61_1   HA61    
label values ha61_2   HA61    
label values ha61_3   HA61    
label values ha61_4   HA61    
label values ha63_1   HA63    
label values ha63_2   HA63    
label values ha63_3   HA63    
label values ha63_4   HA63    
label values ha64_1   HA64    
label values ha64_2   HA64    
label values ha64_3   HA64    
label values ha64_4   HA64    
label values ha65_1   HA65    
label values ha65_2   HA65    
label values ha65_3   HA65    
label values ha65_4   HA65    
label values ha66_1   HA66    
label values ha66_2   HA66    
label values ha66_3   HA66    
label values ha66_4   HA66    
label values ha67_1   HA67    
label values ha67_2   HA67    
label values ha67_3   HA67    
label values ha67_4   HA67    
label values ha68_1   HA68    
label values ha68_2   HA68    
label values ha68_3   HA68    
label values ha68_4   HA68    
label values hc2_1    HC2     
label values hc2_2    HC2     
label values hc2_3    HC2     
label values hc2_4    HC2     
label values hc3_1    HC3     
label values hc3_2    HC3     
label values hc3_3    HC3     
label values hc3_4    HC3     
label values hc4_1    HC4     
label values hc4_2    HC4     
label values hc4_3    HC4     
label values hc4_4    HC4     
label values hc5_1    HC5     
label values hc5_2    HC5     
label values hc5_3    HC5     
label values hc5_4    HC5     
label values hc6_1    HC6     
label values hc6_2    HC6     
label values hc6_3    HC6     
label values hc6_4    HC6     
label values hc7_1    HC7     
label values hc7_2    HC7     
label values hc7_3    HC7     
label values hc7_4    HC7     
label values hc8_1    HC8     
label values hc8_2    HC8     
label values hc8_3    HC8     
label values hc8_4    HC8     
label values hc9_1    HC9     
label values hc9_2    HC9     
label values hc9_3    HC9     
label values hc9_4    HC9     
label values hc10_1   HC10    
label values hc10_2   HC10    
label values hc10_3   HC10    
label values hc10_4   HC10    
label values hc11_1   HC11    
label values hc11_2   HC11    
label values hc11_3   HC11    
label values hc11_4   HC11    
label values hc12_1   HC12    
label values hc12_2   HC12    
label values hc12_3   HC12    
label values hc12_4   HC12    
label values hc13_1   HC13    
label values hc13_2   HC13    
label values hc13_3   HC13    
label values hc13_4   HC13    
label values hc15_1   HC15    
label values hc15_2   HC15    
label values hc15_3   HC15    
label values hc15_4   HC15    
label values hc16_1   HC16    
label values hc16_2   HC16    
label values hc16_3   HC16    
label values hc16_4   HC16    
label values hc27_1   HC27    
label values hc27_2   HC27    
label values hc27_3   HC27    
label values hc27_4   HC27    
label values hc30_1   HC30    
label values hc30_2   HC30    
label values hc30_3   HC30    
label values hc30_4   HC30    
label values hc31_1   HC31    
label values hc31_2   HC31    
label values hc31_3   HC31    
label values hc31_4   HC31    
label values hc33_1   HC33    
label values hc33_2   HC33    
label values hc33_3   HC33    
label values hc33_4   HC33    
label values hc51_1   HC51    
label values hc51_2   HC51    
label values hc51_3   HC51    
label values hc51_4   HC51    
label values hc52_1   HC52    
label values hc52_2   HC52    
label values hc52_3   HC52    
label values hc52_4   HC52    
label values hc53_1   HC53    
label values hc53_2   HC53    
label values hc53_3   HC53    
label values hc53_4   HC53    
label values hc55_1   HC55    
label values hc55_2   HC55    
label values hc55_3   HC55    
label values hc55_4   HC55    
label values hc56_1   HC56    
label values hc56_2   HC56    
label values hc56_3   HC56    
label values hc56_4   HC56    
label values hc57_1   HC57    
label values hc57_2   HC57    
label values hc57_3   HC57    
label values hc57_4   HC57    
label values hc58_1   HC58    
label values hc58_2   HC58    
label values hc58_3   HC58    
label values hc58_4   HC58    
label values hc60_1   HC60    
label values hc60_2   HC60    
label values hc60_3   HC60    
label values hc60_4   HC60    
label values hc61_1   HC61    
label values hc61_2   HC61    
label values hc61_3   HC61    
label values hc61_4   HC61    
label values hc62_1   HC62    
label values hc62_2   HC62    
label values hc62_3   HC62    
label values hc62_4   HC62    
label values hc68_1   HC68    
label values hc68_2   HC68    
label values hc68_3   HC68    
label values hc68_4   HC68    
label values hc70_1   HC70    
label values hc70_2   HC70    
label values hc70_3   HC70    
label values hc70_4   HC70    
label values hc71_1   HC71    
label values hc71_2   HC71    
label values hc71_3   HC71    
label values hc71_4   HC71    
label values hc72_1   HC72    
label values hc72_2   HC72    
label values hc72_3   HC72    
label values hc72_4   HC72    
label values hc73_1   HC73    
label values hc73_2   HC73    
label values hc73_3   HC73    
label values hc73_4   HC73    
